import { useEffect, useState } from 'react';
import { getStats } from '../api/client';
import type { WorkspaceNode, WorkspaceStats, DocumentNode } from '../api/client';
export default function Dashboard({project,node,onOpen,refresh,resources}:{project:string;node?:WorkspaceNode|null;onOpen:(path:string)=>void;refresh:number;resources:DocumentNode[]}) {
  const [stats,setStats]=useState<WorkspaceStats|null>(null);
  const [error,setError]=useState('');
  useEffect(()=>{let active=true;setStats(null);setError('');getStats(project,node?.id).then(value=>{if(active)setStats(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[project,node?.id,node?.targets,refresh]);
  return <div className="dashboard"><span className="eyebrow">{node?'Cluster dashboard':'Workspace overview'}</span><h1>{node?.title||project}</h1><p className="dashboard-subtitle">{node?'A live view of the documents and data connected to this hub.':'Your ideas, their connections, and the places to explore next.'}</p>{error&&<p className="error" role="alert">{error}</p>}{!stats&&!error?<p className="reader-loading" role="status">Gathering your workspace…</p>:stats&&<><div className="stat-grid">{[['Documents',stats.documents],['Connections',stats.connections],['Data nodes',stats.data_nodes],['Unresolved links',stats.unresolved],['Unconnected docs',stats.isolated],['Assets',stats.assets??'—']].map(([label,value])=><article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="dashboard-grid"><section className="dashboard-card"><h2>Most connected ideas</h2>{stats.hubs.length?stats.hubs.map(hub=><button className="hub-row" key={hub.path} onClick={()=>onOpen(hub.path)}><span>{hub.title}<small>{hub.path}</small></span><b>{hub.connections}</b></button>):<p>Connect a few documents to start discovering clusters.</p>}</section><section className="dashboard-card"><h2>Topics in this space</h2>{stats.tags.slice(0,12).map(tag=><div className="topic-row" key={tag.name}><span>{tag.name}</span><div><i style={{width:`${Math.max(4,tag.count/Math.max(stats.documents,1)*100)}%`}}/></div><b>{tag.count}</b></div>)}{stats.tags.length===0&&<p>Folder tags and custom labels appear here.</p>}</section></div>{resources.length>0&&<section className="dashboard-card resource-cards"><h2>{node?'Connected resources':'Data in this workspace'}</h2><div>{resources.map(resource=><button key={resource.path} onClick={()=>onOpen(resource.path)}>▤ {resource.title}<small>Open connected resource ↗</small></button>)}</div></section>}<p className="dashboard-note">{node?'Counts cover this hub’s direct connections; connections count links between its LaTeX documents.':'Counts update from saved documents and workspace nodes. Connections count links between LaTeX documents.'}</p></>}</div>;
}
