import { lazy, Suspense, useEffect, useState } from 'react';
import { getAccounts, connectAccount, disconnectAccount, getResourcePreview, resourcePdfUrl } from '../api/client';
import type { ResourcePreview, WorkspaceNode, AccountConnection } from '../api/client';
const PdfPreview=lazy(()=>import('./PdfPreview'));
export default function DataViewer({project,node,connections,onOpen}:{project:string;node:WorkspaceNode;connections:{path:string;title:string}[];onOpen:(path:string)=>void}) {
  const [preview,setPreview]=useState<ResourcePreview|null>(null);
  const [error,setError]=useState('');
  const [tab,setTab]=useState(0);
  const [version,setVersion]=useState(0);
  const [account,setAccount]=useState<AccountConnection|null>(null);
  useEffect(()=>{let active=true;setPreview(null);setError('');setTab(0);getAccounts().then(accounts=>{if(active)setAccount(accounts.find(value=>value.provider===node.resource?.provider)||null);});getResourcePreview(project,node.id).then(value=>{if(active)setPreview(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[project,node.id,node.resource?.provider,version]);
  const sheet=preview?.sheets?.[tab];
  return <div className="data-viewer"><div className="data-title"><div><span className="eyebrow">{node.resource?.provider==='google'?'Google Drive':'Microsoft OneDrive'} · Read-only</span><h1>{node.title}</h1><p>{node.resource?.name}</p></div><button onClick={()=>setVersion(version+1)}>↻ Refresh</button></div>{connections.length>0&&<nav className="node-links" aria-label="Connected ideas"><span>Connected ideas</span>{connections.map(item=><button key={item.path} onClick={()=>onOpen(item.path)}>{item.title}</button>)}</nav>}{error&&<div className="data-error"><p className="error" role="alert">{error}</p>{account?.configured&&<button onClick={async()=>{try{const value=await connectAccount(account.provider);window.location.assign(value.url);}catch(e){setError(e instanceof Error?e.message:'Could not connect');}}}>Reconnect account</button>}</div>}{!preview&&!error&&<p className="reader-loading" role="status">Opening your connected resource…</p>}{preview?.kind==='pdf'&&<Suspense fallback={<p className="reader-loading">Loading reader…</p>}><PdfPreview key={version} url={resourcePdfUrl(project,node.id)} onOpen={()=>{}}/></Suspense>}{preview?.kind==='document'&&<article className="cloud-document">{preview.paragraphs?.map((paragraph,index)=><p key={index}>{paragraph||'\u00a0'}</p>)}<small>Text preview. Document formatting and images are not reproduced.</small></article>}{preview?.kind==='sheet'&&<><div className="sheet-tabs">{preview.sheets?.map((item,index)=><button key={index} aria-pressed={tab===index} onClick={()=>setTab(index)}>{item.name}</button>)}</div><div className="sheet-table"><table><thead><tr><th>#</th>{sheet?.rows[0]?.map((_,index)=><th key={index}>{column(index)}</th>)}</tr></thead><tbody>{sheet?.rows.map((row,index)=><tr key={index}><th>{index+1}</th>{row.map((cell,key)=><td key={key}>{cell}</td>)}</tr>)}</tbody></table></div><small className="data-footnote">Read-only values; formulas use the workbook’s saved results. {sheet?.truncated||preview.truncated?'Preview limited to 20 sheets, 200 rows and 30 columns.':''}</small></>}{preview?.truncated&&preview.kind==='document'&&<small>Showing the first 2,000 paragraphs.</small>}{account?.connected&&<button className="disconnect-account" onClick={async()=>{try{await disconnectAccount(account.provider);setPreview(null);setError('Account disconnected. Reconnect to view this resource.');setAccount({...account,connected:false});}catch(e){setError(e instanceof Error?e.message:'Could not disconnect');}}}>Disconnect {account.provider==='google'?'Google':'Microsoft'} account</button>}</div>;
}
function column(index:number):string {return index<26?String.fromCharCode(65+index):column(Math.floor(index/26)-1)+String.fromCharCode(65+index%26);}
